### ISSUE TITLE
x86_64平台在安卓5至安卓6闪退

### ISSUE THREAD

**Issue by cnRrex** [lucinhu/bili_you#100]
### Bug 描述

在安卓5.0到6.0，x86_64设备均遇见闪退，即使安装arm版本转译也同样会出问题。
在逍遥模拟器安卓7.1则不会出现闪退。
抓取了Nokia N1 安卓5.1和mumu模拟器安卓6.0的关于这部分的log。
[mumu.log](https://github.com/lucinhu/bili_you/files/11486181/mumu.log)
[nokia-n1.log](https://github.com/lucinhu/bili_you/files/11486182/nokia-n1.log)

### 复现步骤

可以用谷歌Android Studio的x86_64模拟器，使用上述安卓版本复现

### 版本信息

1. Android 版本: 5.0 - 6.0
2. 平台：x86_64
3. 设备: atom平板或安卓模拟器
4. bili_you 版本号: 1.1.1+11至1.1.2+12，1.1.0及以下无闪退。

**Comment by Burial0268** [comment]
红米4 MIUI10 Android6.0.1 同样错误，蹲一手解决

**Comment by 1598266725** [comment]
确实

**Comment by lucinhu** [comment]
media_kit库的问题，这个需要库的作者解决

**Comment by 1598266725** [comment]
> media_kit库的问题，这个需要库的作者解决

那也太难受了，老手机不能用

**Comment by cnRrex** [comment]
> > media_kit库的问题，这个需要库的作者解决
> 
> 那也太难受了，老手机不能用

库的作者已经正在处理了。[https://github.com/alexmercerind/media_kit/issues/210](url)

**Comment by 1598266725** [comment]
> > > media_kit库的问题，这个需要库的作者解决
> > 
> > 那也太难受了，老手机不能用
> 
> 库的作者已经正在处理了。[链接](https://github.com/alexmercerind/media_kit/issues/210)

那真是泰裤啦
