### ISSUE TITLE
通用设置打开是空白的

### ISSUE THREAD

**Issue by 2584191127** [lucinhu/bili_you#15]
![Screenshot_20230318_170750_com lucinhu bili_you](https://user-images.githubusercontent.com/78305714/226096459-3fea86c1-c512-4ae5-8318-387618aedae5.jpg)

**Comment by lucinhu** [comment]
还没写，只是先用来占个位置的

**Comment by 2584191127** [comment]
好的，先star一下，希望以后能取代我手机上的bilibili

**Comment by 2584191127** [comment]
好的，先star一下，希望以后能取代我手机上的bilibili

**Comment by VillagerTom** [comment]
建议在未开发完的页面增添“功能开发中”字样。
