### ISSUE TITLE
密码登录，验证码登录都有bug

### ISSUE THREAD

**Issue by Time34** [lucinhu/bili_you#17]
他都显示成功了，我还登不进去。
![Screenshot_2023-03-21-16-03-58-513_com bilibili app in](https://user-images.githubusercontent.com/128461914/226547951-4e5bcb76-dda5-4059-9f62-b98a284bee9b.jpg)
![Screenshot_2023-03-21-16-03-44-111_com bilibili app in](https://user-images.githubusercontent.com/128461914/226547964-aee6e9e7-b732-4312-bb2e-45a44228f735.jpg)
![Screenshot_2023-03-21-16-03-15-031_com lucinhu bili_you](https://user-images.githubusercontent.com/128461914/226547975-2059b2a7-e2dd-4969-be39-195b08ed96ce.jpg)

**Comment by lucinhu** [comment]
这个bug存在挺久的了，不知道为什么有些人登得进去，有些人登不了。。。

**Comment by julewater** [comment]
希望大佬修复无法登陆的问题，简洁的b战我好喜欢

**Comment by lucinhu** [comment]
https://wwzu.lanzouo.com/ieNNr0qtesha
密码:64v9
新增了网页登陆，试试能不能登陆

**Comment by Time34** [comment]
登录可以了，动态也
![Uploading Screenshot_2023-03-22-23-18-36-560_com.lucinhu.bili_you.jpg…]()
能显示了，但账号界面还是那样

**Comment by Time34** [comment]
![Uploading Screenshot_2023-03-22-23-18-36-560_com.lucinhu.bili_you.jpg…]()

**Comment by lucinhu** [comment]
这个可能是因为还没有加载完？等待几秒或者换个网络？

**Comment by lucinhu** [comment]
现在好了吧

**Comment by Time34** [comment]
好了，感谢大佬
