### ISSUE TITLE
主页无法双列显示

### ISSUE THREAD

**Issue by amokiel** [lucinhu/bili_you#19]
项目截图好像主页可以双列显示内容，不过1.0.7版本登录之后，首页依然是单列显示内容。这算不算是个bug，或者是还没有增加这个功能。辛苦了。

**Comment by lucinhu** [comment]
这是与屏幕大小有关的，小屏手机下可能只有一列

**Comment by lucinhu** [comment]
你手机屏幕多大

**Comment by lucinhu** [comment]
那我改成双列显示吧
