### ISSUE TITLE
希望可以打包一个 iOS 用的 ipa 文件

### ISSUE THREAD

**Issue by CY-Christin** [lucinhu/bili_you#193]
### 预期行为

打包出一个 iOS 用的 ipa 文件，方便在 iPhone 上使用。

### 功能描述

iOS 同步安卓更新，并打包可安装文件。

**Comment by Taosky** [comment]
IOS得签名或者巨魔吧，打包了一个没签名的版本，有需要可以下载试试
https://github.com/Taosky/trollstore-ipa-cn/releases/tag/bili_you
