### ISSUE TITLE
账号无法登陆希望修复

### ISSUE THREAD

**Issue by sanchendumeng** [lucinhu/bili_you#2]
无法登陆

**Comment by lucinhu** [comment]
是用的短信无法登录吗？如果是账号密码登录的，暂时无法解决。

**Comment by lucinhu** [comment]
系统是不是miui? 貌似就miui上有登录不了的情况。

**Comment by sanchendumeng** [comment]
我是摩托罗拉的手机，myui系统

**Comment by sanchendumeng** [comment]
![Screenshot_20230218-130349](https://user-images.githubusercontent.com/48471389/219839996-ce44bb08-9684-4dc9-89ae-057ce97e96a7.png)

**Comment by lucinhu** [comment]
我这里android类原生测试都可以。手头上没有这种系统的手机，还暂时无法测试。🤡

**Comment by sanchendumeng** [comment]
myui就是类原生

**Comment by lucinhu** [comment]
太奇怪了吧

**Comment by lucinhu** [comment]
那视频可以看吗

**Comment by sanchendumeng** [comment]
没事那就再等等 账号登陆功能吧

**Comment by sanchendumeng** [comment]
其他都正常看的 登录不了
