### ISSUE TITLE
希望能有长按倍速的功能

### ISSUE THREAD

**Issue by 2584191127** [lucinhu/bili_you#23]
另外希望推荐视频可以设置成双列展示；还有推荐视频的标题和up名字之间有很大空白，希望能优化一下
![Screenshot_20230325_173440_com lucinhu bili_you_edit_858976489981430](https://user-images.githubusercontent.com/78305714/227709271-2cf4500c-d240-4be0-92c5-6e53359ac162.jpg)

**Comment by lucinhu** [comment]
长按倍数功能的意思是可以设置长按快进的倍数吗？

**Comment by lucinhu** [comment]
长按快进功能现在是有的，固定2倍速

**Comment by 2584191127** [comment]
> 长按快进功能现在是有的，固定2倍速

好像要全屏才有，我一般不全屏看，希望不用全屏也能长按三倍速

**Comment by lucinhu** [comment]
不需要全屏也有长按快进啊

**Comment by lucinhu** [comment]
这个一直都有的

**Comment by 2584191127** [comment]
> 这个一直都有的

刚试了一下确实有😰，我可能以前没看到加速了😂，抱歉抱歉
