### ISSUE TITLE
评论区显示问题

### ISSUE THREAD

**Issue by VillagerTom** [lucinhu/bili_you#29]
评论区被隐藏展示的回复不能点开。

![IMG_20230404_191232.jpg](https://user-images.githubusercontent.com/89803422/230303993-3f026754-5bfe-4996-b090-0d420dc87ddc.jpg)

![IMG_20230404_191108.jpg](https://user-images.githubusercontent.com/89803422/230304208-0ae4fd24-70ce-40a9-a1b3-75f0aad9020a.jpg)

**Comment by lucinhu** [comment]
已修复，下个版本更新
