### ISSUE TITLE
哔哩哔哩番剧出差的番剧视频看不了

### ISSUE THREAD

**Issue by bilibili2233a** [lucinhu/bili_you#3]
我已经开了clash:全局代理规则+全部应用，节点是香港ip，就是无法播放，但是可以加载评论
其他的第三方开源客户端例如:BBLL、bilimiao开香港ip代理都可以看港澳台番剧
![Screenshot_20230218_164432_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/99982054/219851099-81381290-66c6-4706-ade9-a2e308c33568.jpg)

![Screenshot_20230218_164434_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/99982054/219851098-81005af7-4ac5-4819-a5bc-b35365635023.jpg)

**Comment by bilibili2233a** [comment]
用哔哩哔哩的ip检测api
http://api.bilibili.com/x/web-interface/zone
检测到的是香港ip
![Screenshot_20230218_165754_com.kiwibrowser.browser.dev.jpg](https://user-images.githubusercontent.com/99982054/219851620-f90f3201-8f2b-45cc-905c-2615c0e226a0.jpg)

**Comment by lucinhu** [comment]
![Screenshot_20230218-165953_BiliYou](https://user-images.githubusercontent.com/78008990/219851739-e78e5809-677d-40c5-bfe4-02d12327a4b0.png)
我这里试了可以

**Comment by bilibili2233a** [comment]
清除了应用数据，可以播放港澳台了
