### ISSUE TITLE
[BUG]评论区加载失败后无法刷新

### ISSUE THREAD

**Issue by VillagerTom** [lucinhu/bili_you#32]
https://user-images.githubusercontent.com/89803422/230664096-110ac35d-f3e9-4f66-8f48-766669585d5d.mp4

**Comment by VillagerTom** [comment]
https://user-images.githubusercontent.com/89803422/230662992-8ff3cd03-d960-4b31-926f-5302a70ac214.mp4

**Comment by VillagerTom** [comment]
还有楼中楼的刷新，只要断网刷新就会一直卡在刷新状态，即使网络恢复。（虽然可以退出重进）

**Comment by lucinhu** [comment]
下载链接:https://wwp.lanzoup.com/iJAHV0ss5omd  提取码 : bwgr
现在你试试有没有改善

**Comment by VillagerTom** [comment]
@lucinhu 抱歉，没及时看到消息，链接过期了。。（鉴定为玩原神玩的）

**Comment by lucinhu** [comment]
下载链接:https://wwp.lanzoup.com/iR6U30sull3e  提取码 : ddbf

**Comment by lucinhu** [comment]
还有，O怎么你了😡😡

**Comment by VillagerTom** [comment]
> 下载链接:https://wwp.lanzoup.com/iR6U30sull3e  提取码 : ddbf

第一个bug已被消灭，第二个bug依然存活

![Record_2023-04-14-16-41-10_1d5dee2b061ba6e496d3bc6343d81ad6.gif](https://user-images.githubusercontent.com/89803422/231998084-e86a7c6a-b44c-4276-8b77-96f490159806.gif)

（🤤诶嘿嘿，小派蒙，玩坏了直接吃掉！）

**Comment by lucinhu** [comment]
已解决
下载链接:https://wwp.lanzoup.com/iT1OS0ty0k6f  提取码 : ebbw
