### ISSUE TITLE
界面&功能的建议

### ISSUE THREAD

**Issue by bilibili2233a** [lucinhu/bili_you#4]
用了一会之后发现了一些功能和ui要改善的地方，希望可能加上或者改好
打开视频后的评论界面:写在图中了
简介界面:投币应该是个硬币，一个圆形很怪、分享功能直接调起系统的分享菜单（分享链接不要是哔哩哔哩的短链接，av号链接好）、视频显示av号、简介达到一定数字折叠
![IMG_20230218_183949_387.jpg](https://user-images.githubusercontent.com/99982054/219856033-c0c91ded-6628-4689-b3bb-24761d7c3281.jpg)

设置界面:
参考原生设置和其他应用的界面
加上莫奈取色的调色板更改界面颜色、首页的功能自定义显示、后台播放、退出后视频变成画中画开关、播放器设置、首页视频自定义过滤器、评论简介达到一定字数折叠
![Collage_20230218_182854.jpg](https://user-images.githubusercontent.com/99982054/219856246-90aac712-a968-47bf-a0a0-3633e10b61da.jpg)

直播界面:
参考第三方看b站直播应用
![Collage_20230218_183546.jpg](https://user-images.githubusercontent.com/99982054/219856153-fd627b22-f54e-43c2-b828-fa96d4dd447b.jpg)

播放器界面:
弹幕的开关、数量、位置、透明度和屏蔽词功能
分辨率选择、解码选项
画中画

**Comment by lucinhu** [comment]
哇，谢谢。直播界面正愁没参考呢。相关建议会考虑的。

**Comment by bilibili2233a** [comment]
直播界面举例的应用: https://github.com/Jackiu1997/pure_live
设置界面和莫奈取色举例的应用:
https://github.com/Ashinch/ReadYou
