### ISSUE TITLE
自己的评论重复

### ISSUE THREAD

**Issue by bilibili2233a** [lucinhu/bili_you#40]
**描述BUG**
自己发了一条评论，在APP里面刷新了两三次就会出现无限自己评论。

**Bug产生步骤**
重现步骤:
1. 打开哔哩哔哩发评论
2. 回到biliyou看自己的评论
3. 点开刷新2到3次以上。
4.就可以看到无限的重复自己评论

**预期行为**

**截图**
![Screenshot_20230410_032752_com.lucinhu.bili_you_edit_40185383083972.jpg](https://user-images.githubusercontent.com/99982054/230828341-5bb39e8d-9e32-4083-a5f1-682f32147008.jpg)

**设备信息:**
 - 型号: 华为mate20Pro
 - 系统: Android10
 - webview版本:110.0.5481.65 (548106534) 
 - 版本号:1.0.9 (2001)

**Additional context**

**Comment by lucinhu** [comment]
我无法复现这个bug

**Comment by lucinhu** [comment]
我是直接刷不出来

**Comment by bilibili2233a** [comment]
啊这，看来这bug就离谱☹️

**Comment by lucinhu** [comment]
前期代码写得太烂了，没有什么考虑。屎山代码，搞得我都想重做了😂

**Comment by bilibili2233a** [comment]
确实，用flutter的应用总有一种卡卡的感觉。（复制文字的光标不跟手、动画≈没有、用md3的动效没有其他用md3的好）

在32位处理器安卓5.1还闪退

**Comment by lucinhu** [comment]
下载链接:https://wwp.lanzoup.com/iJAHV0ss5omd 提取码 : bwgr
现在应该改好了

**Comment by bilibili2233a** [comment]
打开后:
https://user-images.githubusercontent.com/99982054/231378421-d6fead68-2979-4ac0-895f-b9a082f29c9b.mp4

退出登录的时候卡了一会

无法登录，手动检查登录状态也不行。
![Screenshot_20230412_150316_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/99982054/231378065-95547183-7934-492b-b29d-2cd5e39941a7.jpg)

**Comment by bilibili2233a** [comment]
在哔哩哔哩是显示登录了。
![Screenshot_20230412_151002.jpg](https://user-images.githubusercontent.com/99982054/231379572-888ad4e8-914d-4ba8-a9e7-6c8cea80d3ed.jpg)

**Comment by bilibili2233a** [comment]
试着清除数据后，还是不行
https://user-images.githubusercontent.com/99982054/231386270-94421d4b-c712-4d79-b31f-b2223770ab26.mp4

**Comment by lucinhu** [comment]
下载链接:https://wwp.lanzoup.com/iH6Y00staere  提取码 : ae3v

**Comment by bilibili2233a** [comment]
现在安装了之后，退出登录再登录就能正常登录了。
自己的评论也不会出现重复了
问题已解决😘
https://user-images.githubusercontent.com/99982054/231445535-c32a0f3f-00ce-4092-81bd-f5e4d691c97b.mp4
