### ISSUE TITLE
UI 动态 番剧解锁

### ISSUE THREAD

**Issue by Arlene947** [lucinhu/bili_you#41]
1.动态图视频 隐藏动态(比如自己的抽奖)
![Screenshot_2023-04-10-13-52-06-166_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/128675053/230841151-ea1dc271-38fd-47d1-bf70-9af5544542f3.jpg)![Screenshot_2023-04-10-13-52-19-104_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/128675053/230841240-194060e2-df4a-4d91-878c-255c1ec0b9b0.jpg)

2.设置的UI有点挤 类似蓝云的这种
-![Screenshot_2023-04-10-14-33-16-508_com.tooyoung.lanzou.jpg](https://user-images.githubusercontent.com/128675053/230841922-e9ba3505-69c2-41da-87e2-10cea293675f.jpg)

![IMG_20230410_143340.jpg](https://user-images.githubusercontent.com/128675053/230841925-f38457b4-cf46-4615-b408-87face25684e.jpg)

![Screenshot_2023-04-10-14-33-13-420_com.tooyoung.lanzou.jpg](https://user-images.githubusercontent.com/128675053/230841926-315fce71-3a05-4ae5-8a7c-83f8aaa2120d.jpg)

3.多账号切换 自定义
4.类似漫游 直接把港澳台番剧放在 番剧的二类下 多整点自定义开关呗 众口难调毕竟

**Comment by Arlene947** [comment]
佬 啥时候整个电报群或者频道吧

**Comment by lucinhu** [comment]
电报群是有的，只不过不怎么上

**Comment by lucinhu** [comment]
港澳台番剧这个功能我担心牵涉到版权问题，，，

**Comment by Arlene947** [comment]
> 电报群是有的，只不过不怎么上

推个链接吧 吹水啥的也方便

**Comment by lucinhu** [comment]
https://t.me/bili_you_app

**Comment by lucinhu** [comment]
其实自己搜bili_you也能搜到
