### ISSUE TITLE
不能打开视频,不登录的时候可以,登陆了就不行了

### ISSUE THREAD

**Issue by creazytom** [lucinhu/bili_you#45]
**描述BUG**
清楚而简介的bug描述.

**Bug产生步骤**
重现步骤:

**预期行为**

**截图**

**设备信息:**
 - 型号: [如小米10]
 - 系统: [如Android13]
 - webview版本: 
 - 版本号 [如v1.0.7]

**Additional context**

**Comment by lucinhu** [comment]
我没遇见过这个问题，无法排查该bug🙃
