### ISSUE TITLE
看视频看多了就会闪退

### ISSUE THREAD

**Issue by bilibili2233a** [lucinhu/bili_you#50]
**描述BUG**
连续在视频里面多次点击下方的视频推荐，然后一直看下去就会闪退。

**Bug产生步骤**
重现步骤:

1.打开biliyou看视频
2.从下方的视频推荐里面一直看。
3.看久了，首先会出现处理器频率拉满的情况
4.继续往下看就会发现自己的网速一直很高，内存也是一直越来越高占用率，接着就闪退回到桌面，桌面崩溃。
预期行为

**截图**
[录屏视频](https://youtu.be/wT03RJ6CAKk)
由于Github不支持超过10 MB以上的上传，只能通过外链

**设备信息:**

型号: 华为mate20Pro
系统: Android10
webview版本:110.0.5481.65 (548106534)
版本号:1.0.9 (2001)

**Comment by lucinhu** [comment]
这是已知的bug，是因为跳转页面后播放器没有释放导致的

**Comment by bilibili2233a** [comment]
不知道这篇有没有用:
[播放器性能优化之路](https://juejin.cn/post/6898867991161602061)

**Comment by lucinhu** [comment]
软解的方式，可以打开比较多的视频页面了。
下载链接:https://wwp.lanzoup.com/iT1OS0ty0k6f  提取码 : ebbw

**Comment by bilibili2233a** [comment]
确实可以看很多视频了，关了硬解后，可以在30个视频以上连续播放了
录屏视频：没了，占用95%就会自动关闭录屏

使用硬解后20个视频内必卡死
