### ISSUE TITLE
版本号问题

### ISSUE THREAD

**Issue by VillagerTom** [lucinhu/bili_you#52]
软件升级的版本号判定功能是不是有问题？你之前发给我的v1.1.0，每次打开都提示让我升级到v1.0.9，今天你发布了- v1.1.0后提示才消失。

**Comment by lucinhu** [comment]
正常，只是判断当前版本和release的版本是否一致。

**Comment by VillagerTom** [comment]
还有每次安装新版本系统都告诉我“您已安装相同版本”![Screenshot_2023-04-16-22-28-23-36.jpg](https://user-images.githubusercontent.com/89803422/232320550-61fcd242-5757-4faa-8453-b3821ee4371a.jpg)

**Comment by lucinhu** [comment]
按数字判断也可以实现，但感觉没什么必要就没搞

**Comment by VillagerTom** [comment]
> 正常，只是判断当前版本和release的版本是否一致。

还是搞一下比较好，不然测试的时候比较搞心态😂

**Comment by VillagerTom** [comment]
> 按数字判断也可以实现，但感觉没什么必要就没搞

方便回档测试（
