### ISSUE TITLE
在某些时段似乎无法加载视频

### ISSUE THREAD

**Issue by mcLYX** [lucinhu/bili_you#57]
### Bug 描述

点入视频后，显示灰色重试，无法获取视频

### 复现步骤

目前能正常播放，无法复现，概率/时段性问题，也许是啊b干的

### 预期行为

正常点开播放视频（目前正常）

### 版本信息

1. Android 版本: 12
2. Webview 版本: 98
3. 设备型号: LG G820
4. bili_you 版本号: 1.1.0

**Comment by lucinhu** [comment]
现在的新版本是否有所改善？

**Comment by mcLYX** [comment]
> 现在的新版本是否有所改善？

似乎有，现在都能打开，
但是从1.1.1开始（换了播放器?），我的一个安卓5.0的低配设备播放视频2秒后闪退，刚更的1.1.2也是。
另外有一个奇怪的现象，在1.1.0加载不了视频时，在同一网络下使用另一台设备用1.1.1之后的版本随便打开一个视频，那么在之后1.1.0也能正常播放
有个BBLL的客户端也类似，直接播放视频显示Source Error，但随便点开一个直播后再播放视频就正常
