### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by Jacket1608** [lucinhu/bili_you#65]
有时候首页和动态一直在刷新，内容出不来![Screenshot_2023-04-29-09-02-03-982_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/61339228/235274459-e6ec437e-e680-4743-a22b-2c12dbc8bac3.jpg)

![Screenshot_2023-04-29-09-01-59-233_com.lucinhu.bili_you.jpg](https://user-images.githubusercontent.com/61339228/235274462-719adacf-3f9a-4f54-bfca-07f138efa23b.jpg)

**Comment by lucinhu** [comment]
现在的新版本是否有改善？
