### ISSUE TITLE
特定视频比例错误

### ISSUE THREAD

**Issue by xzsk2** [lucinhu/bili_you#66]
### Bug 描述

![图片](https://user-images.githubusercontent.com/20642596/235285914-75a384d1-9db3-43ab-974e-6e39b937e8b7.png)
![图片](https://user-images.githubusercontent.com/20642596/235285918-026bdb7c-8e80-4cb9-9565-b4974e4a9e62.png)

### 复现步骤

打开av739976855，4k的1P竖屏全屏均比例错误
切换到1080p的2P后比例依旧错误，进入全屏后正常，退出全屏后依然正常
此时再切换到1P，比例正常，进入全屏后比例错误，退出依旧错误

测试了其他的视频并没有出现类似的问题

### 版本信息

1. Android 版本: YAAP 13
2. Webview 版本: 112.0.5615.136
3. 设备型号: OnePlus 7
4. bili_you 版本号: 1.1.1

**Comment by lucinhu** [comment]
第一p的视频源本身就是4:3的比例:
![Screenshot_20230429_141853-1](https://user-images.githubusercontent.com/78008990/235287366-ba997ef6-423b-4bb9-aa77-d9e9a5dbc395.png)
第二p的视频源则是正常的16:9的比例:
![Screenshot_20230429_142015](https://user-images.githubusercontent.com/78008990/235287381-e51859ab-2a68-46b8-a285-47932216ef93.png)
所以刚进入视频时的比例显示是正常的.
当切换第2p时,  由于控制比例的控件没有刷新, 所以还是第1p的比例.
再切换为全屏时, 由于控制比例的控件刷新了, 才变为第2p的比例.

**Comment by lucinhu** [comment]
![Screenshot_20230429_142955](https://user-images.githubusercontent.com/78008990/235287644-ebe8ac90-f4a8-40ed-955f-ed1b833a48bc.png)
所以这里的bug其实是视频比例没有根据sar恢复成正常比例.
还有另一个bug: 分p切换后没有及时更新比例, 没有考虑到不同的分p比例不同.

**Comment by lucinhu** [comment]
已完成
