### ISSUE TITLE
进度条相关问题

### ISSUE THREAD

**Issue by BeautyyuYanli** [lucinhu/bili_you#79]
### Bug 描述

1. 视频进度条拖动时略显滞塞
2. 软件启动后第一次打开视频，进度条会是 00:00/00:00，第二次及以后正常

### 复现步骤

无

### 版本信息

1. Android 版本: 13
2. Webview 版本: 112.0.5615.135
3. 设备型号: OnePlus 8
4. bili_you 版本号: 1.1.1

**Comment by lucinhu** [comment]
这是因为没有加载完成。现在的版本在加载完成后进度条正常了。
