### ISSUE TITLE
可以弄一下跨平台吗？来个windows和macos端。

### ISSUE THREAD

**Issue by KYKY548** [lucinhu/bili_you#91]
### 预期行为

可以弄一下跨平台吗？来个windows和macos端。这个和底层应该没什么关联，应该不难吧

### 功能描述

可以弄一下跨平台吗？来个windows和macos端。这个和底层应该没什么关联，应该不难吧

**Comment by lucinhu** [comment]
编译不难，但是不同的平台可能会有不同的bug，调试和处理bug比较麻烦。

**Comment by lucinhu** [comment]
当然如果你能帮忙编译那是相当欢迎的

**Comment by TPAXcc** [comment]
windows 有现成的完成度比这个项目高
